### ISSUE TITLE
Duda de enunciado

### ISSUE THREAD

**Issue by smdevesa** [PI-ITBA/TPE#16]
Buenas noches, queria consultar a que se refieren con:

Resolver todas las consultas con una única lectura de archivo y de una sola vez. No se aceptarán implementaciones que ofrezcan un menú de opciones o similar que permita al usuario decidir cuál de las consultas desea procesar. 

La parte de la lectura queda clara, pero no entiendo cual seria la limitación con hacer las consultas "de una sola vez", si se refiere a hacer todas las querys al mismo tiempo o puedo separar ya teniendo los datos almacenados en query1/query2/query3.

Desde ya muchas gracias.

**Comment by marcelogarberoglio** [comment]
Se refiere a la ejecución, no a cómo lo implementen. El ejecutable debe recibir los parámetros y una vez que finalice tienen que estar creados todos los archivos pedidos.
