### ISSUE TITLE
Consulta Formato Fechas

### ISSUE THREAD

**Issue by nick0aran** [PI-ITBA/TPE#20]
¡Buenas tardes!
Tenia una consulta acerca del formato de los .csv. Cuando dice _"Se asume que el formato y contenido de los archivos es correcto."_, ¿se asume tambien que las fechas que te pasan son correctas? Es decir, ¿hace falta verificar el si end_year es anterior a start_year o si te pasan un dia incorrecto para el mes donde estás situado? Desde ya, muchas gracias.

**Comment by marcelogarberoglio** [comment]
Las fechas son parte del contenido de los archivos, así que sí, se asume que son fechas correctas.

**Comment by nick0aran** [comment]
Perfecto, mil gracias
