### ISSUE TITLE
Duda acerca del aborto del programa

### ISSUE THREAD

**Issue by smdevesa** [PI-ITBA/TPE#24]
Buenas noches, tengo entendido que el programa no debería abortar en bajo ninguna circunstancia y hay que mostrar el error correspondiente, sin embargo, quería saber si cuando hacemos el frontend seria correcto decidir que este aborte ante un error de memoria o simplemente hay que mostrar el error y dejar que siga corriendo. Gracias.

**Comment by marcelogarberoglio** [comment]
El frontend puede decidir finalizar con la ejecución si el error que se produce hace que no tenga sentido seguir ejecutando.
