### ISSUE TITLE
Front o Back

### ISSUE THREAD

**Issue by nick0aran** [PI-ITBA/TPE#32]
Buen dia,
Tenia una duda acerca de si la lectura de los archivos .csv es parte del front, ya que en la consigna menciona que el mismo se encarga de la "lectura y preparación de los datos" pero no sabia si esto se refería únicamente a los argumentos recibidos por linea de comando o a los archivos en sí. Gracias!

**Comment by marcelogarberoglio** [comment]
El enunciado además dice:
El back-end debería servir también para otros front-ends, como por ejemplo mostrar la información por pantalla, en forma de gráficos, o que la información sea leída por teclado o desde una base de datos.

Cuando se menciona "lectura y preparación de los datos" no hace referencia a los argumentos, sino a los datos para las queries (estaciones, alquileres)
