### ISSUE TITLE
Archivos como parametros

### ISSUE THREAD

**Issue by Nbellavitis** [PI-ITBA/TPE#39]
Hola buenas noches, queria saber si el orden en cual se mandan los archivos como parametro seria siempre el mismo o tendriamos que verificar cual es  cual.
gracias

**Comment by marcelogarberoglio** [comment]
Tienen que respetar el orden que está en el enunciado.

" Por ejemplo para procesar los datos de 🇨🇦, si el archivo CSV de alquileres se llama bikes.csv​, el de estaciones se llama stations.csv y​ ambos están en el mismo directorio que el ejecutable bikeSharingMON, el programa **se debe** invocar como: 

$> ​./bikeSharingMON bikes.csv stations.csv "

Dice "se debe", no "se puede"

**Comment by Nbellavitis** [comment]
perfecto, gracias!
