### ISSUE TITLE
Viajes que comienzan y terminar en la misma estación

### ISSUE THREAD

**Issue by martinAleB** [PI-ITBA/TPE#44]
Buenas tardes, espero que estén muy bien.
Quería consultar si, en caso de que existan viajes que comiencen y terminen en una misma estación, estos debieran verse reflejados en la query 2. Es decir, si debería haber una columna en el HTML y csv que sea A A cantidad cantidad.
Desde ya muchas gracias!

**Comment by fmeola** [comment]
Hola Martín.
En el enunciado de la Query 2 dice:

**No se deben listar los viajes circulares, es decir donde la estación A y B es la misma.**

**Comment by martinAleB** [comment]
Excelente, muchas gracias!
