### ISSUE TITLE
Abortar en el front

### ISSUE THREAD

**Issue by fardenghi** [PI-ITBA/TPE#50]
Hola buenas, cuando el front decide que el programa debe abortar, se debe enviar un mensaje a la salida estandar y a la salida de error? o solo a una de ellas?

**Comment by marcelogarberoglio** [comment]
Siendo el front, puede ser cualquiera de las dos. A ambas no tiene mucho sentido.

**Comment by fardenghi** [comment]
Muchas Gracias!
