### ISSUE TITLE
Flags en la entrega

### ISSUE THREAD

**Issue by peposalinas** [PI-ITBA/TPE#56]
Buenas tardes, quería consultar si debemos incluir los flags con los que compilamos durante el desarrollo del proyecto en el Makefile para la entrega o si es correcto entregarlo sin esos flags que resultan innecesarios una vez que el trabajo esta terminado.
Desde ya muchas gracias.

**Comment by marcelogarberoglio** [comment]
Sí.
![image](https://github.com/PI-ITBA/TPE/assets/13138167/87758af3-5dd3-4d09-a69d-1a2204be7224)

Si bien esos flags no se usan en producción, nosotros queremos evaluar el trabajo con esos flags.
