### ISSUE TITLE
Archivos de prueba

### ISSUE THREAD

**Issue by martinAleB** [PI-ITBA/TPE#58]
Buenas tardes, espero que esten muy bien.
Hago esta pregunta solo para estar seguro. En la consigna menciona que no se deben subir archivos de prueba, esto quiere decir que a la hora de la entrega debemos desestimar subir cualquier tipo de prueba unitaria que hayamos hecho para probar?
Desde ya muchas gracias y saludos.

**Comment by marcelogarberoglio** [comment]
La consigna dice "archivos de prueba publicados". Muchas veces incluyen en la entrega los mismos archivos csv que publicamos nosotros, nunca entendí bien por qué.

**Comment by martinAleB** [comment]
Aah, excelente entonces. Muchísimas gracias!
