### ISSUE TITLE
Conformación de grupos

### ISSUE THREAD

**Issue by anita476** [PI-ITBA/TPE#6]
Hola, ¿qué tal? 
Quería saber de cuántas personas se recomienda que sean los grupos más o menos. 
Gracias!

**Comment by marcelogarberoglio** [comment]
Está en la consigna la cantidad máxima de integrantes. Depende de cada uno decidir si prefiere armar grupos con menos integrantes.

**Comment by anita476** [comment]
Perdón no había visto eso en las consignas, muchas gracias!
