### ISSUE TITLE
Flexibilidad backend

### ISSUE THREAD

**Issue by maximocitba** [PI-ITBA/TPE#62]
Queria consultar, si es necesario que el backend pueda soportar un front distinto el cual primero carga todos los viajes y luego por ejemplo le pide al usuarion con getint que ingrese el rango de anios para las queries 4 y 5, o podemos suponer que siempre el front va a haber consultado el rango de anios antes de empezar a cargar datos y el back exigir que el rango este presente para empezar a utilizarlo.

**Comment by marcelogarberoglio** [comment]
Pueden asumir que el rango de años se establece desde un principio, y que el backend sólo deberá procesar datos que estén dentro de ese rango de años.

**Comment by maximocitba** [comment]
Mil gracias marce
